version: '3'
services:
  db:
    image: postgres:14.1
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_reg_DB
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 9002:5432
  spring-api:
    build:
      context: ./back
    ports:
      - "9001:9001"
    container_name: spring-api
    stdin_open: true
  react-ui:
    build:
      context: ./frontV2
      args:
        REACT_APP_BACK_END_URL: http://localhost:9001/
        #REACT_APP_BACK_END_URL: http://spring-api:9001/
    ports:
      - "9000:80"
    container_name: react-ui
    stdin_open: true

# TODO: Add proper env variables