version: '2'
services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user_reg_DB
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 9003:5432