spring:
  datasource:
    username: "root"
    password: "root"
    url: jdbc:postgresql://db/user_reg_DB
    driverClassName: org.postgresql.Driver
server:
  port : 9001

FRONT_URL: "http://react-ui:9000/"