spring:
  datasource:
    username: "root"
    password: "root"
#    url: jdbc:postgresql://db:5432/user_reg_DB
    url: { SPRING_DATASOURCE_URL }
    driverClassName: org.postgresql.Driver
server:
  port : 9001

FRONT_URL: "http://react-ui:9000/"