spring:
  datasource:
    username: "root"
    password: "root"
    url: jdbc:postgresql://${SPRING_DB_URL}
    driverClassName: org.postgresql.Driver
server:
  port : 9001

FRONT_URL: ${SPRING_REACT_UI_URL}
